add doh
qiniu/happy-dns-objc pull request #73
Opened 2021-07-29 03:46 UTC by YangSen-qn

2021-07-29 03:53 UTC, YangSen-qn reviewed
done

2021-08-02 03:44 UTC, bachue requested changes

2021-08-02 03:44 UTC, bachue commented on HappyDNS/Dns/QNDnsResponse.m
> +- (void)prase:(NSError **)error {
@YangSen-qn `prase` => `parse`

2021-08-02 03:44 UTC, bachue commented on HappyDNS/Dns/QNDnsUdpResolver.m
> +    int messageId = arc4random()%(0xFFFF);
@YangSen-qn 这里确认 messageId 可以是用随机值吗？无需去重吗？

2021-08-02 03:44 UTC, bachue commented on HappyDNS/Doh/QNDohResolver.m
> +    int messageId = arc4random()%(0xFFFF);
@YangSen-qn 这里确认 messageId 可以是用随机值吗？无需去重吗？

2021-08-02 03:44 UTC, bachue commented on HappyDNSTests/DnsServerResolverTest.m
> +- (void)testMutiDnsServer {
@YangSen-qn `Muti` => `Multi`

2021-08-02 03:44 UTC, bachue commented on HappyDNSTests/DohResolverTest.m
> +- (void)testMutiDnsServer {
@YangSen-qn `Muti` => `Multi`

2021-08-02 03:44 UTC, bachue commented on HappyDNS/Http/QNDnspodFree.h
> +DEPRECATED_MSG_ATTRIBUTE("use initWithServer: instead, because tencent 119.29.29.29 will invalid at 2021/01/01");
@YangSen-qn 既然是发布新版本 就直接移除这个无法使用的类吧

2021-08-02 03:44 UTC, bachue commented on HappyDNS/Dns/QNDnsUdpResolver.m
> +        [socket bindToPort:[self refreshPort] error: &error];
@YangSen-qn 这里可以尝试用 0 也就是操作系统决定端口号

2021-08-16 03:50 UTC, YangSen-qn commented on HappyDNS/Dns/QNDnsUdpResolver.m
> +    int messageId = arc4random()%(0xFFFF);
messageId 只是一个

2021-08-16 06:13 UTC, bachue approved these changes

2021-08-23 11:11 UTC, bachue approved these changes

2021-08-31 02:52 UTC, merged